# Generated by Django 5.2.8 on 2025-12-20 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="pay_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
