# Generated by Django 5.2.8 on 2025-12-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_payment_pay_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="pay_amount",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
