# Generated by Django 5.2.8 on 2025-12-20 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_payment_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                default="open", max_length=25, verbose_name="Статус платежа"
            ),
        ),
    ]
