# Generated by Django 5.2.8 on 2025-12-20 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_payment_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="session_id",
            field=models.CharField(
                blank=True,
                max_length=255,
                null=True,
                verbose_name="ID платежа в stripe",
            ),
        ),
    ]
