# Generated by Django 5.2.8 on 2025-12-20 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0005_alter_subscription_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="amount",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Стоимость курса"
            ),
        ),
    ]
