# Generated by Django 5.2.8 on 2025-12-20 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0006_course_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="amount",
            field=models.PositiveIntegerField(
                default=1000, verbose_name="Стоимость урока"
            ),
        ),
    ]
