# Generated by Django 5.2.9 on 2025-12-24 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0007_lesson_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="last_update",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
